[build]
target = "xtensa-esp32-none-elf"

[target.xtensa-esp32-none-elf]
runner = "espflash flash --monitor"
rustflags = [
    "-C", "link-arg=-nostartfiles",
    "-C", "link-arg=-Tlinkall.x",
    "-C", "force-frame-pointers",
]

[unstable]
# esp toolchain ships rust-src; build core+alloc from source for Xtensa.
build-std = ["alloc", "core"]

[env]
ESP_LOG = "info"
